name: crazy-md
services:
  - name: crazy-md
    type: web
    git:
      branch: main
    build:
      buildpack: nodejs
    run:
      command: npm start
    ports:
      - port: 3000
        protocol: http
    env:
      - key: PORT
        value: "3000"
      - key: NODE_ENV
        value: production
    scaling:
      min: 1
      max: 1
